version: '3'
services:
  aptly:
    container_name: aptly
    image: lcas.lincoln.ac.uk/lcas/aptly-dev:master
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: unless-stopped

    ports:
      - 8088:80

    # Create aptly-data volume,
    # otherwise use directory, fe:
    # - ./aptly-data:/opt/aptly
    volumes:
      - ./aptly-data:/opt/aptly

    # If want to use additional environments,
    # you can set them in .env file
  cron:
    container_name: aptly-cron
    image: lcas.lincoln.ac.uk/lcas/aptly-cron:master
    build:
      context: ./cronjobs
      dockerfile: ./Dockerfile.cron
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

